Script started on Sat Mar  8 15:58:45 2014
[?1034h[1m[32m[jharvard@appliance ~/cs161/os161/submit/asst2[35m (master)[32m]$(B[m kr
sys161: System/161 release 1.99.07, compiled Feb 23 2014 15:46:25

OS/161 base system version 1.99.07
Copyright (c) 2000, 2001, 2002, 2003, 2004, 2005, 2008, 2009
   President and Fellows of Harvard College.  All rights reserved.

Puffin OS system version 0 (ASST2 #153)

3824k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0

cpu0: MIPS/161 (System/161 2.x) features 0x0
cpu1: MIPS/161 (System/161 2.x) features 0x0
cpu2: MIPS/161 (System/161 2.x) features 0x0
cpu3: MIPS/161 (System/161 2.x) features 0x0
buffers: max count 2048; max size 1024k
OS/161 kernel [? for menu]: p testbin/badcall
[a-|, 1-4, *, ?=menu, !=quit]
[a] execv                   [b] waitpid                 
[c] open                    [d] read                    
[e] write                   [f] close                   
[g] reboot                  [h] sbrk                    
[i] ioctl                   [j] lseek                   
[k] fsync                   [l] ftruncate               
[m] fstat                   [n] remove                  
[o] rename                  [p] link                    
[q] mkdir                   [r] rmdir                   
[s] chdir                   [t] getdirentry             
[u] symlink                 [v] readlink                
[w] dup2                    [x] pipe                    
[y] __time                  [z] __getcwd                
[{] stat                    [|] lstat                   
[1] asst1                   [2] asst2                   
[3] asst3                   [4] asst4                   
[*] all                     [!] quit                    
Choose: 2
[execv]
(program name unknown): passed: exec NULL
(program name unknown): passed: exec invalid pointer
(program name unknown): passed: exec kernel pointer
(program name unknown): passed: exec the empty string
(program name unknown): passed: exec /bin/true with NULL arglist
(program name unknown): passed: exec /bin/true with invalid pointer arglist
(program name unknown): passed: exec /bin/true with kernel pointer arglist
(program name unknown): passed: exec /bin/true with invalid pointer arg
(program name unknown): passed: exec /bin/true with kernel pointer arg
[waitpid]
(program name unknown): passed: wait for pid -8
(program name unknown): passed: wait for pid -1
(program name unknown): passed: pid zero
(program name unknown): passed: nonexistent pid
(program name unknown): passed: wait with NULL status
(program name unknown): UH-OH: fork failed: Out of memory
(program name unknown): UH-OH: fork failed: Out of memory
(program name unknown): UH-OH: fork failed: Out of memory
(program name unknown): UH-OH: fork failed: Out of memory
(program name unknown): passed: wait for self: No child processes
(program name unknown): UH-OH: can't fork: Out of memory
(program name unknown): UH-OH: can't fork: Out of memory
[open]
(program name unknown): passed: open with NULL path
(program name unknown): passed: open with invalid-pointer path
(program name unknown): passed: open with kernel-pointer path
(program name unknown): passed: open null: with bad flags
(program name unknown): passed: open empty string
[read]
(program name unknown): passed: read using fd -1
(program name unknown): passed: read using fd -5
(program name unknown): passed: read using closed fd
(program name unknown): passed: read using impossible fd
(program name unknown): passed: read using fd OPEN_MAX
(program name unknown): passed: read with NULL buffer
Unknown syscall 68
(program name unknown): passed: read with invalid buffer
Unknown syscall 68
(program name unknown): passed: read with kernel-space buffer
Unknown syscall 68
[write]
(program name unknown): passed: write using fd -1
(program name unknown): passed: write using fd -5
(program name unknown): passed: write using closed fd
(program name unknown): passed: write using impossible fd
(program name unknown): passed: write using fd OPEN_MAX
(program name unknown): passed: write with NULL buffer
Unknown syscall 68
(program name unknown): passed: write with invalid buffer
Unknown syscall 68
(program name unknown): passed: write with kernel-space buffer
Unknown syscall 68
[close]
(program name unknown): passed: close using fd -1
(program name unknown): passed: close using fd -5
(program name unknown): passed: close using closed fd
(program name unknown): passed: close using impossible fd
(program name unknown): passed: close using fd OPEN_MAX
[reboot]
(program name unknown): NOTICE: if this kills the system, it's a failure.
(program name unknown): passed: reboot with invalid flags
[lseek]
(program name unknown): passed: lseek using fd -1
(program name unknown): passed: lseek using fd -5
(program name unknown): passed: lseek using closed fd
(program name unknown): passed: lseek using impossible fd
(program name unknown): passed: lseek using fd OPEN_MAX
(program name unknown): passed: lseek on device
(program name unknown): UH-OH: fork failed: Out of memory
(program name unknown): passed: lseek to negative offset
Unknown syscall 68
(program name unknown): passed: seek past/to EOF
Unknown syscall 68
(program name unknown): passed: lseek with invalid whence code
Unknown syscall 68
[chdir]
(program name unknown): passed: chdir with NULL path
(program name unknown): passed: chdir with invalid-pointer path
(program name unknown): passed: chdir with kernel-pointer path
(program name unknown): passed: chdir to empty string
[dup2]
(program name unknown): passed: dup2 using fd -1
(program name unknown): passed: dup2 using fd -5
(program name unknown): passed: dup2 using closed fd
(program name unknown): passed: dup2 using impossible fd
(program name unknown): passed: dup2 using fd OPEN_MAX
(program name unknown): passed: dup2 to -1
(program name unknown): passed: dup2 to -5
(program name unknown): passed: dup2 to impossible fd
(program name unknown): passed: dup2 to OPEN_MAX
(program name unknown): passed: dup2 to same fd
Unknown syscall 82
(program name unknown): passed: lseek fd after dup2 to itself
[__getcwd]
(program name unknown): passed: getcwd with NULL buffer
(program name unknown): passed: getcwd with invalid buffer
(program name unknown): passed: getcwd with kernel-space buffer
Choose: e
(program name unknown): passed: write using fd -1
(program name unknown): passed: write using fd -5
(program name unknown): passed: write using closed fd
(program name unknown): passed: write using impossible fd
(program name unknown): passed: write using fd OPEN_MAX
(program name unknown): passed: write with NULL buffer
Unknown syscall 68
(program name unknown): passed: write with invalid buffer
Unknown syscall 68
(program name unknown): passed: write with kernel-space buffer
Unknown syscall 68
Choose: x
Unknown syscall 46
(program name unknown): ------: pipe with NULL pointer (unimplemented)
Unknown syscall 46
(program name unknown): ------: pipe with invalid pointer (unimplemented)
Unknown syscall 46
(program name unknown): ------: pipe with kernel pointer (unimplemented)
Unknown syscall 46
(program name unknown): passed: pipe with unaligned pointer: Function not implemented
Choose: i
Unknown syscall 64
(program name unknown): ------: ioctl using fd -1 (unimplemented)
Unknown syscall 64
(program name unknown): ------: ioctl using fd -5 (unimplemented)
Unknown syscall 64
(program name unknown): ------: ioctl using closed fd (unimplemented)
Unknown syscall 64
(program name unknown): ------: ioctl using impossible fd (unimplemented)
Unknown syscall 64
(program name unknown): ------: ioctl using fd OPEN_MAX (unimplemented)
Unknown syscall 64
(program name unknown): ------: invalid ioctl (unimplemented)
Choose: 
[1m[32m[jharvard@appliance ~/cs161/os161/submit/asst2[35m (master)[32m]$(B[m exit [K
exit

Script done on Sat Mar  8 15:59:08 2014
