Script started on Sat Mar  8 16:00:11 2014
[?1034h[1m[32m[jharvard@appliance ~/cs161/os161/submit/asst2[35m (master)[32m]$(B[m kr
sys161: System/161 release 1.99.07, compiled Feb 23 2014 15:46:25

OS/161 base system version 1.99.07
Copyright (c) 2000, 2001, 2002, 2003, 2004, 2005, 2008, 2009
   President and Fellows of Harvard College.  All rights reserved.

Puffin OS system version 0 (ASST2 #153)

3824k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0

cpu0: MIPS/161 (System/161 2.x) features 0x0
cpu1: MIPS/161 (System/161 2.x) features 0x0
cpu2: MIPS/161 (System/161 2.x) features 0x0
cpu3: MIPS/161 (System/161 2.x) features 0x0
buffers: max count 2048; max size 1024k
OS/161 kernel [? for menu]: p testbin/badcall
[a-|, 1-4, *, ?=menu, !=quit]
[a] execv                   [b] waitpid                 
[c] open                    [d] read                    
[e] write                   [f] close                   
[g] reboot                  [h] sbrk                    
[i] ioctl                   [j] lseek                   
[k] fsync                   [l] ftruncate               
[m] fstat                   [n] remove                  
[o] rename                  [p] link                    
[q] mkdir                   [r] rmdir                   
[s] chdir                   [t] getdirentry             
[u] symlink                 [v] readlink                
[w] dup2                    [x] pipe                    
[y] __time                  [z] __getcwd                
[{] stat                    [|] lstat                   
[1] asst1                   [2] asst2                   
[3] asst3                   [4] asst4                   
[*] all                     [!] quit                    
Choose: j
(program name unknown): passed: lseek using fd -1
(program name unknown): passed: lseek using fd -5
(program name unknown): passed: lseek using closed fd
(program name unknown): passed: lseek using impossible fd
(program name unknown): passed: lseek using fd OPEN_MAX
(program name unknown): passed: lseek on device
(program name unknown): passed: lseek stdin when open on file (try 1)
(program name unknown): passed: lseek stdin when open on file (try 2)
Unknown syscall 68
(program name unknown): passed: lseek to negative offset
Unknown syscall 68
(program name unknown): passed: seek past/to EOF
Unknown syscall 68
(program name unknown): passed: lseek with invalid whence code
Unknown syscall 68
Choose: 
[1m[32m[jharvard@appliance ~/cs161/os161/submit/asst2[35m (master)[32m]$(B[m exit
exit

Script done on Sat Mar  8 16:00:24 2014
