Script started on Sat Mar  8 15:48:16 2014
[?1034h[1m[32m[jharvard@appliance ~/cs161/os161/submit/asst2[35m (master)[32m]$(B[m kr
sys161: System/161 release 1.99.07, compiled Feb 23 2014 15:46:25

OS/161 base system version 1.99.07
Copyright (c) 2000, 2001, 2002, 2003, 2004, 2005, 2008, 2009
   President and Fellows of Harvard College.  All rights reserved.

Puffin OS system version 0 (ASST2 #153)

7920k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0

cpu0: MIPS/161 (System/161 2.x) features 0x0
cpu1: MIPS/161 (System/161 2.x) features 0x0
cpu2: MIPS/161 (System/161 2.x) features 0x0
cpu3: MIPS/161 (System/161 2.x) features 0x0
buffers: max count 4096; max size 2048k
OS/161 kernel [? for menu]: s
(program name unknown): Timing enabled.
OS/161$ cp sys161.conf sys161.cong f.copy
(program name unknown): subprocess time: 0.253240680 seconds
OS/161$ 
[1m[32m[jharvard@appliance ~/cs161/os161/submit/asst2[35m (master)[32m]$(B[m cdr
[1m[32m[jharvard@appliance ~/cs161/root[35m[32m]$(B[m ls
DISK1.img  badcallfile  [0m[38;5;27mbin[0m      [38;5;27mhostinclude[0m  [38;5;51mkernel[0m        [38;5;34mkernel-ASST1[0m  [38;5;34mkernel-CLASS-2-4[0m  [38;5;27mman[0m  [38;5;27msbin[0m      sys161.conf       [38;5;27mtestbin[0m
DISK2.img  bigfile      [38;5;27mhostbin[0m  [38;5;27minclude[0m      [38;5;34mkernel-ASST0[0m  [38;5;34mkernel-ASST2[0m  [38;5;27mlib[0m               s    sometest  sys161.conf.copy
[1m[32m[jharvard@appliance ~/cs161/root[35m[32m]$(B[m diff sys161.conf sys161.conf.copy 
[1m[32m[jharvard@appliance ~/cs161/root[35m[32m]$(B[m cd -
/home/jharvard/cs161/os161/submit/asst2
[1m[32m[jharvard@appliance ~/cs161/os161/submit/asst2[35m (master)[32m]$(B[m ^C
[1m[32m[jharvard@appliance ~/cs161/os161/submit/asst2[35m (master)[32m]$(B[m exit
exit

Script done on Sat Mar  8 15:48:53 2014
