Script started on Sat Mar  8 15:46:31 2014
[?1034h[1m[32m[jharvard@appliance ~/cs161/os161/submit/asst2[35m (master)[32m]$(B[m kr
sys161: System/161 release 1.99.07, compiled Feb 23 2014 15:46:25

OS/161 base system version 1.99.07
Copyright (c) 2000, 2001, 2002, 2003, 2004, 2005, 2008, 2009
   President and Fellows of Harvard College.  All rights reserved.

Puffin OS system version 0 (ASST2 #153)

7920k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0

cpu0: MIPS/161 (System/161 2.x) features 0x0
cpu1: MIPS/161 (System/161 2.x) features 0x0
cpu2: MIPS/161 (System/161 2.x) features 0x0
cpu3: MIPS/161 (System/161 2.x) features 0x0
buffers: max count 4096; max size 2048k
OS/161 kernel [? for menu]: tt3
Starting thread test 3 (5 [sleepalots], 2 {computes}, 1 waker)
[1][0][2]{0: 205}{1: 147}[3][4][2][1]{0: 22}[4][2]{1: 98}[3][0][2][1][0][4][2][1][3]{0: 107}[3]{1: 58}[2][1][4][0][3][1][2][0][1]{0: 132}{1: 124}[4][2][3][0][0][1][3][2]{0: 173}{1: 84}[4][1][3][0][2][1][0]{0: 225}[4]{1: 20}[2][3][2]{0: 170}[1][4]{1: 242}[2][0][3][0][4][1]{0: 151}[2][3]{1: 190}[2][1][3][0][4]{0: 92}{1: 30}[0][2][3][1][4][3]{0: 14}[2][4][3][1][4][3][0][2][1][4][3][1][4][3][1][4][3][4][1][3][4][1][0][4][4][2][0][2]{1: 103}[0][0][0][0]
Thread test 3 done
Operation took 6.450814840 seconds
OS/161 kernel [? for menu]: 
[1m[32m[jharvard@appliance ~/cs161/os161/submit/asst2[35m (master)[32m]$(B[m exit
exit

Script done on Sat Mar  8 15:46:47 2014
